plugins {
	id 'java'
	id 'idea'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.harborview'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springModulithVersion', "2.0.6")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.0.1'
	implementation 'org.springframework.modulith:spring-modulith-starter-core'
	implementation 'org.postgresql:postgresql'
	implementation 'com.blazegraph:colt:2.1.4'
	implementation 'org.htmlunit:htmlunit:5.0.0'
	implementation 'org.apache.httpcomponents.client5:httpclient5:5.6.1'

	implementation 'com.github.ben-manes.caffeine:caffeine:3.2.4'

	//---------------- BEGIN Logging ----------------
	implementation 'org.springframework.boot:spring-boot-starter-log4j2'
	implementation 'com.lmax:disruptor:4.0.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-mail-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-thymeleaf-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:4.0.1'
	testImplementation 'org.springframework.modulith:spring-modulith-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


dependencyManagement {
	imports {
		mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

//--------------------------- Integration tests ---------------------------

tasks.register('integrationTest', Test) {
	description = "Run integration tests"
	group = "verification"
	testClassesDirs = sourceSets.integration.output.classesDirs
	classpath = sourceSets.integration.runtimeClasspath
	systemProperty('spring.profiles.active', 'integration')
}

sourceSets {
	integration  {
		java {
			compileClasspath += sourceSets.main.output + sourceSets.test.output
			runtimeClasspath += sourceSets.main.output + sourceSets.test.output
			srcDirs = ['src/integration/java']
		}
	}
}

tasks.named('integrationTest') {
	useJUnitPlatform()
}


idea {
	module {
		testSources.from(sourceSets.integration.java.srcDirs)
	}
}

//--------------------------- Configuration s---------------------------

configurations {
	all {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
	}
	integrationImplementation.extendsFrom(testImplementation)
	integrationRuntimeOnly.extendsFrom(testRuntimeOnly)
}

