#-------------------- Spring Data Source ----------------------
spring.datasource.url = jdbc:postgresql://172.20.1.6:5432/trader
spring.datasource.username = trader
spring.datasource.password = ok
spring.sql.init.platform = postgresql
spring.datasource.driver-class-name = org.postgresql.Driver

#-------------------- Resources ----------------------
# static content from filesystem first
spring.web.resources.static-locations[0]=file:src/main/resources/static/
spring.web.resources.static-locations[1]=file:src/main/resources/
spring.web.resources.static-locations[2]=classpath:/static/

#-------------------- Thymeleaf ----------------------
#----------- Use the file:/ prefix, or spring.thymeleaf.cache = false will not work
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.thymeleaf.cache=false

#-------------------- SSL Bundle ----------------------
# server.ssl.enabled=false

#-------------------- Log Level ----------------------
logging.level.org.springframework.modulith=DEBUG
