spring.application.name=harborview4

#-------------------- MyBatis ----------------------
mybatis.config-location=classpath:mybatis/mybatis.config.xml


#-------------------- SSL Bundle ----------------------
# server.ssl.enabled=false

#-------------------- Log Level ----------------------
#logging.level.org.springframework.modulith=DEBUG

#-------------------- Adapters ----------------------
adapter.stockmarket.from-date=2000-01-01

#-------------------- Redis ----------------------
redis.host=172.20.1.2
redis.port=6379
redis.db=0
redis.fetchOpeningPrice=true

#-------------------- Caffeine ----------------------
# Minutes
cache.options.expiry.minutes=5
# Seconds
cache.option.expiry.seconds=30

#-------------------- Nordnet ----------------------
nordnet.curdate=today

#-------------------- Spring ----------------------
spring.profiles.active=local
spring.cache.type=NONE
server.port=8080
