spring.application.name=harborview4

#-------------------- MyBatis ----------------------
mybatis.config-location=classpath:mybatis/mybatis.config.xml

spring.cache.type=NONE

#-------------------- SSL Bundle ----------------------
# server.ssl.enabled=false

#-------------------- Log Level ----------------------
#logging.level.org.springframework.modulith=DEBUG

spring.profiles.active=local