
#-------------------- Spring Data Source ----------------------
spring.datasource.url = jdbc:postgresql://172.20.1.8:5432/trader_itest
spring.datasource.username = trader
spring.datasource.password = ok
spring.sql.init.platform = postgresql
spring.datasource.driver-class-name = org.postgresql.Driver

#-------------------- Resources ----------------------
# static content from filesystem first
spring.web.resources.static-locations[0]=file:src/main/resources/static/
spring.web.resources.static-locations[1]=classpath:/static/

#-------------------- MyBatis ----------------------
mybatis.config-location=classpath:mybatis/mybatis-integration.config.xml

spring.cache.type=NONE

#-------------------- SSL Bundle ----------------------
# server.ssl.enabled=false

#-------------------- Log Level ----------------------
logging.level.org.springframework.modulith=DEBUG
